name: Build
on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Yarn Cache
        uses: c-hive/gha-yarn-cache@v1
      - name: Install Dependencies
        run: yarn install --force
      - name: Run Linter
        run: yarn lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Yarn Cache
        uses: c-hive/gha-yarn-cache@v1
      - name: Install Dependencies
        run: yarn install --force
      - name: Run Unit Tests
        run: yarn test
  release:
    name: Release
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Yarn Cache
        uses: c-hive/gha-yarn-cache@v1
      - name: Install Dependencies
        run: yarn install --force
      - name: Build
        run: yarn build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
  docs:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
      - name: Yarn Cache
        uses: c-hive/gha-yarn-cache@v1
      - name: Install Dependencies
        run: yarn install --force
      - name: Build Content
        run: yarn docs:build
      - name: Publish
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: docs/.vuepress/dist
          branch: gh-pages
          token: ${{ secrets.PAGES_TOKEN }}
